# -*- coding: utf-8 -*-
"""DASHBOARD SKRIPSI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nw8owPd2XwTI8cFPUB0N0OBM3yIhcAEw

# **DATASET**
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
import seaborn as sns
import itertools

# DOWNLOAD DATA YAHOO FINANCE
tickers = {
    'USD_IDR': 'IDR=X',       # Target Prediksi
    'DXY': 'DX-Y.NYB',        # Indeks Kekuatan US Dollar Global
    'IHSG': '^JKSE',          # Sentimen Pasar Saham Domestik
    'Emas': 'GC=F',           # Harga Emas Global (Safe Haven)
    'Minyak': 'CL=F'          # Harga Minyak Mentah Dunia (WTI Crude Oil)
}

# 5 tahun ke belakang
data_raw = yf.download(
    list(tickers.values()),
    start="2021-01-01",
    end="2026-05-28",
    interval="1d"
)
df = data_raw['Close'].copy().rename(columns={v: k for k, v in tickers.items()})

# Cleaning
df = df.ffill().bfill().reset_index()
df['Date'] = df['Date'].dt.tz_localize(None)

# Simpan dataframe ke file Excel
df.to_excel("Data_Market_YahooFinance.xlsx", index=False)

print("Data berhasil disimpan ke Data_Market_YahooFinance.xlsx")

df.head()

df.describe()

df.info()
df.shape

df.isnull().sum()

df.duplicated().sum()

# 3.1 Info tipe data & pengecekan nilai kosong / duplikat
print(df.info())
print("\nJumlah missing value per kolom:\n", df.isna().sum())
print("\nJumlah tanggal duplikat:", df["Date"].duplicated().sum())

"""## Penyamaan Frekuensi Data (Business Day) & Pengisian Tanggal yang Hilang

Mengisi 4 tanggal yang hilang yaitu


*   1 Januari 2025
*   18 April 2025
*   25 Desember 2025
*   1 Januari 2026
"""

# Urutkan berdasarkan tanggal & jadikan Date sebagai index waktu
df = df.sort_values("Date").reset_index(drop=True)
df.set_index("Date", inplace=True)

# Samakan ke frekuensi hari bursa (Business day) agar index memiliki frekuensi eksplisit
# dibutuhkan agar ARIMA (statsmodels) dapat mengindeks hasil forecast dengan benar.
df = df.asfreq("B")
print("Missing value setelah disamakan ke frekuensi 'B' (hari libur bursa akan muncul sbg NaN):")
print(df.isna().sum())

# Isi hari libur bursa dengan nilai perdagangan terakhir (forward-fill),
# pendekatan standar untuk data pasar keuangan.
df = df.ffill()
print("\nMissing value setelah forward-fill:\n", df.isna().sum())

print(f"\nRentang data: {df.index.min().date()} s/d {df.index.max().date()}  ({len(df)} observasi)")
df.describe().T

"""# **EDA**"""

# Visualisasi seluruh variabel
fig, axes = plt.subplots(5, 1, figsize=(14, 16), sharex=True)
cols = ["USD_IDR", "Minyak", "DXY", "Emas", "IHSG"]
titles = ["Nilai Tukar Rupiah/USD (Y)", "Harga Minyak (Brent)", "Indeks Dolar AS (DXY)",
          "Harga Emas", "Indeks Harga Saham Gabungan (IHSG)"]
for ax, col, title in zip(axes, cols, titles):
    ax.plot(df.index, df[col], linewidth=1)
    ax.set_title(title)
    ax.set_ylabel(col)
plt.xlabel("Tanggal")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6.5, 5.5))
corr = df[cols].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0, square=True, cbar_kws={'shrink': 0.8})
plt.title('Matriks Korelasi Antar Variabel', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

print("Korelasi terhadap USD_IDR (diurutkan):")
print(corr['USD_IDR'].sort_values(ascending=False))

# Rolling mean & rolling std pada USD_IDR -- indikasi visual (non-)stasioneritas
window = 30
roll_mean = df["USD_IDR"].rolling(window).mean()
roll_std = df["USD_IDR"].rolling(window).std()

plt.figure(figsize=(14, 5))
plt.plot(df["USD_IDR"], label="USD_IDR", linewidth=1)
plt.plot(roll_mean, label=f"Rolling Mean ({window} hari)", linewidth=2)
plt.plot(roll_std, label=f"Rolling Std ({window} hari)", linewidth=2)
plt.legend()
plt.title("USD_IDR — Rolling Mean & Rolling Std\n(mean yang terus bergeser mengindikasikan data tidak stasioner)")
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
sns.histplot(df['USD_IDR'], kde=True, ax=axes[0], color='#1f77b4')
axes[0].set_title('Distribusi Kurs USD/IDR')
sns.boxplot(x=df['USD_IDR'], ax=axes[1], color='#1f77b4')
axes[1].set_title('Boxplot Kurs USD/IDR (deteksi outlier)')
plt.tight_layout()
plt.show()

"""## Pembagian Data (Train-Test Split)"""

target = "USD_IDR"
n = len(df)
train_size = int(n * 0.80)

train, test = df.iloc[:train_size], df.iloc[train_size:]

print(f"Data latih : {train.index.min().date()} s/d {train.index.max().date()}  ({len(train)} observasi)")
print(f"Data uji   : {test.index.min().date()} s/d {test.index.max().date()}  ({len(test)} observasi)")

"""## Uji Stasioneritas — Augmented Dickey-Fuller (ADF)"""

def adf_report(series, name):
    result = adfuller(series.dropna(), autolag="AIC")
    return {
        "Variabel": name,
        "ADF Statistic": result[0],
        "p-value": result[1],
        "Lag digunakan": result[2],
        "Kesimpulan (alpha=10%)": "Stasioner" if result[1] < 0.10 else "Tidak Stasioner"
    }

y_train = train[target]

adf_table = pd.DataFrame([
    adf_report(y_train, "Level"),
    adf_report(y_train.diff(), "Differencing ke-1"),
    adf_report(y_train.diff().diff(), "Differencing ke-2"),
])
adf_table

"""# **Model ARIMA**"""

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.stats.stattools import jarque_bera

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, mean_absolute_error

d = 1
y_diff = y_train.diff(d).dropna()

fig, axes = plt.subplots(1, 2, figsize=(14, 4))
plot_acf(y_diff, lags=20, ax=axes[0])
axes[0].set_title(f"ACF — USD_IDR (differencing ke-{d})")
plot_pacf(y_diff, lags=20, ax=axes[1], method="ywm")
axes[1].set_title(f"PACF — USD_IDR (differencing ke-{d})")
plt.tight_layout()
plt.show()

"""**Cara membaca plot:** orde `p` (AR) dilihat dari lag terakhir PACF yang signifikan (keluar dari
pita biru), orde `q` (MA) dilihat dari lag terakhir ACF yang signifikan. Sebagai pelengkap sekaligus
validasi silang, sel berikut melakukan **grid search** kandidat model ARIMA di sekitar orde yang
teridentifikasi, lalu memilih model terbaik berdasarkan MAPE pada data testing.

## Penentuan Parameter & Model ARIMA Terbaik
"""

p_range = range(0, 4)
q_range = range(0, 4)
d_candidates = sorted(set([d, 1, 2]))   # sertakan d hasil ADF + 1 & 2 sebagai pembanding

results = []
for d_ in d_candidates:
    for p_, q_ in itertools.product(p_range, q_range):
        if p_ == 0 and q_ == 0:
            continue
        try:
            fitted = ARIMA(y_train, order=(p_, d_, q_)).fit()
            fc = fitted.forecast(steps=len(test))
            mape_val = mean_absolute_percentage_error(test[target], fc) * 100
            results.append({"order": (p_, d_, q_), "AIC": fitted.aic, "MAPE_test(%)": mape_val})
        except Exception:
            continue

arima_results = pd.DataFrame(results).sort_values("MAPE_test(%)").reset_index(drop=True)
arima_results.head(10)

best_order = arima_results.iloc[0]["order"]
print("Model ARIMA terbaik berdasarkan MAPE data testing: ARIMA", best_order)

best_arima = ARIMA(y_train, order=best_order).fit()
print(best_arima.summary())

arima_forecast = best_arima.forecast(steps=len(test))
arima_forecast.index = test.index

plt.figure(figsize=(14, 5))
plt.plot(train.index[-100:], y_train[-100:], label="Data Latih (100 hari terakhir)")
plt.plot(test.index, test[target], label="Aktual (Data Uji)", color="black")
plt.plot(test.index, arima_forecast, label=f"Prediksi ARIMA{best_order}", color="red", linestyle="--")
plt.legend()
plt.title(f"Hasil Peramalan ARIMA{best_order} vs Aktual")
plt.show()

arima_mape = mean_absolute_percentage_error(test[target], arima_forecast) * 100
arima_rmse = float(np.sqrt(mean_squared_error(test[target], arima_forecast)))
arima_mae = float(mean_absolute_error(test[target], arima_forecast))
print(f"MAPE : {arima_mape:.2f}%")
print(f"RMSE : {arima_rmse:,.2f}")
print(f"MAE  : {arima_mae:,.2f}")

"""## Uji Kelayakan Model ARIMA Terbaik

- **Uji white noise**: plot ACF residual (tidak ada lag signifikan → tidak ada autokorelasi sisaan)
  serta uji formal Ljung-Box.
- **Uji normalitas**: histogram residual (pola lonceng) serta uji formal Jarque-Bera.
"""

residuals = best_arima.resid

fig, axes = plt.subplots(1, 2, figsize=(14, 4))
plot_acf(residuals, lags=20, ax=axes[0])
axes[0].set_title("ACF Residual — Model ARIMA Terbaik")
axes[1].hist(residuals, bins=30, edgecolor="black")
axes[1].set_title("Histogram Residual (Uji Normalitas)")
plt.tight_layout()
plt.show()

lb_test = acorr_ljungbox(residuals, lags=[10, 20], return_df=True)
print("Uji Ljung-Box (H0: residual white noise / tidak ada autokorelasi):\n", lb_test)

jb_stat, jb_p, skew, kurt = jarque_bera(residuals)
print(f"\nUji Jarque-Bera (H0: residual berdistribusi normal): "
      f"statistik={jb_stat:.2f}, p-value={jb_p:.4f}")

"""# **Model LSTM**

Agar perbandingan dengan ARIMA adil (apples-to-apples), LSTM tahap ini **hanya menggunakan riwayat
USD_IDR itu sendiri** sebagai input (univariat), sama seperti informasi yang dipakai ARIMA.
Model LSTM multivariat (dengan variabel Minyak, DXY, Emas, IHSG) tidak saya gunakan.
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 5)

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

LOOKBACK = 30   # jumlah hari historis yang "dilihat" model untuk memprediksi 1 hari ke depan

scaler = MinMaxScaler(feature_range=(0, 1))
train_scaled = scaler.fit_transform(train[[target]])
full_scaled = scaler.transform(df[[target]])

def create_sequences(data, lookback):
    X, y = [], []
    for i in range(lookback, len(data)):
        X.append(data[i - lookback:i, 0])
        y.append(data[i, 0])
    return np.array(X), np.array(y)

X_train, y_train_lstm = create_sequences(train_scaled, LOOKBACK)
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))

# Sertakan LOOKBACK hari terakhir data latih sebagai konteks awal utk memprediksi hari pertama data uji
test_input = full_scaled[train_size - LOOKBACK:]
X_test, y_test_lstm = create_sequences(test_input, LOOKBACK)
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

print("Shape X_train:", X_train.shape, " | Shape X_test:", X_test.shape)

"""## Membangun & Melatih Model LSTM"""

tf.random.set_seed(SEED)

model_lstm = Sequential([
    LSTM(64, activation="tanh", return_sequences=True, input_shape=(LOOKBACK, 1)),
    Dropout(0.2),
    LSTM(32, activation="tanh"),
    Dropout(0.2),
    Dense(1)
])

model_lstm.compile(optimizer="adam", loss="mse")
model_lstm.summary()

early_stop = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

history = model_lstm.fit(
    X_train, y_train_lstm,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)

plt.figure(figsize=(10, 4))
plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.legend()
plt.title("Kurva Loss Model LSTM")
plt.xlabel("Epoch")
plt.ylabel("MSE (skala ternormalisasi)")
plt.show()

"""## Evaluasi Model LSTM"""

y_pred_scaled = model_lstm.predict(X_test)
y_pred_lstm = scaler.inverse_transform(y_pred_scaled).flatten()
y_true_lstm = scaler.inverse_transform(y_test_lstm.reshape(-1, 1)).flatten()

plt.figure(figsize=(14, 5))
plt.plot(test.index[:len(y_pred_lstm)], y_true_lstm, label="Aktual (Data Uji)", color="black")
plt.plot(test.index[:len(y_pred_lstm)], y_pred_lstm, label="Prediksi LSTM", color="green", linestyle="--")
plt.legend()
plt.title("Hasil Peramalan LSTM vs Aktual")
plt.show()

lstm_mape = mean_absolute_percentage_error(y_true_lstm, y_pred_lstm) * 100
lstm_rmse = float(np.sqrt(mean_squared_error(y_true_lstm, y_pred_lstm)))
lstm_mae = float(mean_absolute_error(y_true_lstm, y_pred_lstm))
print(f"MAPE : {lstm_mape:.2f}%")
print(f"RMSE : {lstm_rmse:,.2f}")
print(f"MAE  : {lstm_mae:,.2f}")

"""# **ARIMA vs LSTM**"""

comparison = pd.DataFrame({
    "Model": [f"ARIMA{best_order}", "LSTM (univariat)"],
    "MAPE (%)": [arima_mape, lstm_mape],
    "RMSE": [arima_rmse, lstm_rmse],
    "MAE": [arima_mae, lstm_mae],
}).sort_values("MAPE (%)").reset_index(drop=True)
comparison

plt.figure(figsize=(14, 5))
plt.plot(test.index, test[target], label="Aktual", color="black", linewidth=2)
plt.plot(test.index, arima_forecast, label=f"ARIMA{best_order}", linestyle="--")
plt.plot(test.index[:len(y_pred_lstm)], y_pred_lstm, label="LSTM (univariat)", linestyle="--")
plt.legend()
plt.title("Perbandingan Prediksi ARIMA vs LSTM terhadap Data Aktual")
plt.show()

print(f"Model dengan MAPE terkecil (data uji): {comparison.iloc[0]['Model']} "
      f"({comparison.iloc[0]['MAPE (%)']:.2f}%)")

"""# **Prediksi Kedepan**"""

comparison_full = comparison.sort_values("MAPE (%)").reset_index(drop=True)
comparison_full

FORECAST_DAYS = 30  # jumlah hari bursa ke depan yang ingin diramalkan
best_model_name = comparison_full.iloc[0]["Model"]
future_dates = pd.bdate_range(start=df.index[-1] + pd.Timedelta(days=1), periods=FORECAST_DAYS)

if best_model_name.startswith("ARIMA"):
    final_model = ARIMA(df[target], order=best_order).fit()
    future_forecast = final_model.forecast(steps=FORECAST_DAYS)
    future_forecast.index = future_dates

else:
    # Refit LSTM univariat terbaik pada SELURUH data (train+test), lalu forecast rekursif
    full_scaled_all = scaler.fit_transform(df[[target]])
    X_all, y_all = create_sequences(full_scaled_all, LOOKBACK)
    X_all = X_all.reshape((X_all.shape[0], X_all.shape[1], 1))

    final_lstm = Sequential([
        LSTM(64, activation="tanh", return_sequences=True, input_shape=(LOOKBACK, 1)),
        Dropout(0.2),
        LSTM(32, activation="tanh"),
        Dropout(0.2),
        Dense(1)
    ])
    final_lstm.compile(optimizer="adam", loss="mse")
    final_lstm.fit(X_all, y_all, epochs=100, batch_size=32,
                    callbacks=[EarlyStopping(monitor="loss", patience=10, restore_best_weights=True)],
                    verbose=0)

    window = full_scaled_all[-LOOKBACK:].reshape(1, LOOKBACK, 1)
    preds_scaled = []
    for _ in range(FORECAST_DAYS):
        next_val = final_lstm.predict(window, verbose=0)[0, 0]
        preds_scaled.append(next_val)
        window = np.append(window[:, 1:, :], [[[next_val]]], axis=1)

    future_forecast = pd.Series(
        scaler.inverse_transform(np.array(preds_scaled).reshape(-1, 1)).flatten(),
        index=future_dates
    )

plt.figure(figsize=(14, 5))
plt.plot(df.index[-120:], df[target][-120:], label="Data Historis (120 hari terakhir)")
plt.plot(future_forecast.index, future_forecast.values,
         label=f"Peramalan {FORECAST_DAYS} Hari ke Depan ({best_model_name})",
         color="red", linestyle="--", marker="o", markersize=3)
plt.legend()
plt.title("Peramalan Nilai Tukar Rupiah/USD ke Depan")
plt.show()

future_forecast_df = future_forecast.round(0).rename("Ramalan_USD_IDR").to_frame()
future_forecast_df

"""# **Kesimpulan**"""

print("=" * 70)
print("RINGKASAN PERBANDINGAN MODEL")
print("=" * 70)
print(comparison_full.to_string(index=False))

print(f"\nModel dengan performa TERBAIK (MAPE terkecil pada data uji): "
      f"{comparison_full.iloc[0]['Model']}  (MAPE = {comparison_full.iloc[0]['MAPE (%)']:.2f}%)")

print("\nPedoman interpretasi nilai MAPE (Lewis, 1982):")
print("  < 10%   : peramalan sangat akurat")
print("  10-20%  : peramalan baik")
print("  20-50%  : peramalan layak/cukup")
print("  > 50%   : peramalan tidak akurat")

"""# **Implementasi Dashboard**"""

# ============================================================
# EKSPOR DATA UNTUK DASHBOARD STREAMLIT
# (Tidak mengubah variabel/pipeline di atas — hanya membaca & menyimpan)
# ============================================================
import os
import pandas as pd
import numpy as np

os.makedirs("dashboard_data", exist_ok=True)

# 1) Data aktual historis (USD_IDR)
df_hist_export = df.reset_index()[["Date", target]].copy()
df_hist_export.to_csv("dashboard_data/dashboard_actual.csv", index=False)

# 2) Prediksi ARIMA & LSTM pada periode data uji
df_test_export = pd.DataFrame({"Date": test.index})
df_test_export["ARIMA"] = arima_forecast.values

lstm_pred_full = pd.Series(index=test.index, dtype=float)
lstm_pred_full.iloc[:len(y_pred_lstm)] = y_pred_lstm
df_test_export["LSTM"] = lstm_pred_full.values

df_test_export.to_csv("dashboard_data/dashboard_test_predictions.csv", index=False)

# 3) Peramalan ke depan (future forecast)
df_future_export = pd.DataFrame({
    "Date": future_forecast.index,
    "Forecast": future_forecast.values
})
df_future_export.to_csv("dashboard_data/dashboard_future_forecast.csv", index=False)

# 4) Tabel perbandingan model
comparison_full.to_csv("dashboard_data/dashboard_model_comparison.csv", index=False)

# 5) Metadata (nama model terbaik, order ARIMA terbaik, dsb.)
meta = pd.DataFrame([{
    "best_order": str(best_order),
    "best_model_name": comparison_full.iloc[0]["Model"],
}])
meta.to_csv("dashboard_data/dashboard_meta.csv", index=False)

print("Data untuk dashboard berhasil diekspor ke folder 'dashboard_data/':")
for f in os.listdir("dashboard_data"):
    print(" -", f)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# """
# Dashboard Interaktif — Peramalan Nilai Tukar USD/IDR (ARIMA vs LSTM)
# =====================================================================
# Cara menjalankan:
#     1. Pastikan folder `dashboard_data/` (hasil ekspor dari notebook SKRIPSI)
#        berada satu direktori dengan file ini.
#     2. Install dependensi:
#            pip install streamlit plotly pandas
#     3. Jalankan:
#            streamlit run streamlit_app.py
# """
# 
# import pandas as pd
# import numpy as np
# import plotly.graph_objects as go
# import streamlit as st
# 
# # --------------------------------------------------------------------------
# # KONFIGURASI HALAMAN
# # --------------------------------------------------------------------------
# st.set_page_config(
#     page_title="Dashboard Prediksi Kurs USD/IDR",
#     page_icon="📈",
#     layout="wide",
# )
# 
# DATA_DIR = "dashboard_data"
# 
# 
# # --------------------------------------------------------------------------
# # LOAD DATA (hasil ekspor dari notebook, tidak mengubah pipeline aslinya)
# # --------------------------------------------------------------------------
# @st.cache_data
# def load_data():
#     df_hist = pd.read_csv(f"{DATA_DIR}/dashboard_actual.csv", parse_dates=["Date"])
#     df_test = pd.read_csv(f"{DATA_DIR}/dashboard_test_predictions.csv", parse_dates=["Date"])
#     df_future = pd.read_csv(f"{DATA_DIR}/dashboard_future_forecast.csv", parse_dates=["Date"])
#     df_compare = pd.read_csv(f"{DATA_DIR}/dashboard_model_comparison.csv")
#     meta = pd.read_csv(f"{DATA_DIR}/dashboard_meta.csv").iloc[0]
#     return df_hist, df_test, df_future, df_compare, meta
# 
# 
# try:
#     df_hist, df_test, df_future, df_compare, meta = load_data()
# except FileNotFoundError:
#     st.error(
#         "File data belum ditemukan. Jalankan seluruh sel di notebook `SKRIPSI.ipynb` "
#         "(termasuk sel ekspor data dashboard di bagian paling akhir) terlebih dahulu, "
#         "lalu pastikan folder `dashboard_data/` berada di direktori yang sama dengan "
#         "`streamlit_app.py` ini."
#     )
#     st.stop()
# 
# best_order = meta["best_order"]
# best_model_name = meta["best_model_name"]
# 
# 
# # --------------------------------------------------------------------------
# # HEADER
# # --------------------------------------------------------------------------
# st.title("📈 Dashboard Peramalan Kurs USD/IDR")
# st.caption("Perbandingan Model ARIMA vs LSTM")
# 
# min_date = df_hist["Date"].min().date()
# max_date = df_future["Date"].max().date()
# 
# # --------------------------------------------------------------------------
# # SIDEBAR — KONTROL INTERAKTIF
# # --------------------------------------------------------------------------
# st.sidebar.header("⚙️ Pengaturan Tampilan")
# 
# default_start = max(min_date, (df_hist["Date"].max() - pd.Timedelta(days=180)).date())
# date_range = st.sidebar.date_input(
#     "Rentang tanggal grafik",
#     value=(default_start, max_date),
#     min_value=min_date,
#     max_value=max_date,
# )
# 
# if isinstance(date_range, tuple) and len(date_range) == 2:
#     start_d, end_d = date_range
# else:
#     start_d, end_d = min_date, max_date
# 
# st.sidebar.markdown("**Tampilkan garis:**")
# show_actual = st.sidebar.checkbox("Data Aktual", value=True)
# show_arima = st.sidebar.checkbox("Prediksi ARIMA (data uji)", value=True)
# show_lstm = st.sidebar.checkbox("Prediksi LSTM (data uji)", value=True)
# show_future = st.sidebar.checkbox("Peramalan ke Depan", value=True)
# 
# st.sidebar.markdown("---")
# st.sidebar.subheader("🔎 Cek Nilai pada Tanggal Tertentu")
# selected_date = st.sidebar.date_input(
#     "Pilih tanggal",
#     value=max_date,
#     min_value=min_date,
#     max_value=max_date,
# )
# 
# st.sidebar.markdown("---")
# st.sidebar.subheader("🏆 Model Terbaik")
# st.sidebar.success(f"{best_model_name}\n\nMAPE terkecil pada data uji")
# 
# 
# # --------------------------------------------------------------------------
# # FILTER DATA SESUAI RENTANG TANGGAL
# # --------------------------------------------------------------------------
# def filter_range(df):
#     return df[(df["Date"].dt.date >= start_d) & (df["Date"].dt.date <= end_d)]
# 
# 
# hist_f = filter_range(df_hist)
# test_f = filter_range(df_test)
# future_f = filter_range(df_future)
# 
# 
# # --------------------------------------------------------------------------
# # GRAFIK UTAMA (interaktif — zoom, hover, pan)
# # --------------------------------------------------------------------------
# fig = go.Figure()
# 
# if show_actual:
#     fig.add_trace(go.Scatter(
#         x=hist_f["Date"], y=hist_f["USD_IDR"],
#         name="Aktual", line=dict(color="black", width=2),
#     ))
# if show_arima:
#     fig.add_trace(go.Scatter(
#         x=test_f["Date"], y=test_f["ARIMA"],
#         name=f"ARIMA{best_order}", line=dict(color="orange", width=2, dash="dash"),
#     ))
# if show_lstm:
#     fig.add_trace(go.Scatter(
#         x=test_f["Date"], y=test_f["LSTM"],
#         name="LSTM (univariat)", line=dict(color="green", width=2, dash="dash"),
#     ))
# if show_future:
#     fig.add_trace(go.Scatter(
#         x=future_f["Date"], y=future_f["Forecast"],
#         name="Peramalan ke Depan", line=dict(color="red", width=2, dash="dot"),
#         mode="lines+markers", marker=dict(size=4),
#     ))
# 
# sel_ts = pd.Timestamp(selected_date)
# if start_d <= selected_date <= end_d:
#     fig.add_vline(x=sel_ts, line_width=1, line_dash="dot", line_color="gray")
# 
# fig.update_layout(
#     height=520,
#     xaxis_title="Tanggal",
#     yaxis_title="Kurs USD/IDR",
#     hovermode="x unified",
#     legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
#     margin=dict(l=10, r=10, t=30, b=10),
# )
# 
# st.plotly_chart(fig, use_container_width=True)
# 
# 
# # --------------------------------------------------------------------------
# # NILAI PADA TANGGAL TERPILIH (mencari tanggal bursa terdekat)
# # --------------------------------------------------------------------------
# st.subheader(f"📅 Detail Nilai — {selected_date.strftime('%d %B %Y')}")
# 
# all_dates = pd.concat([df_hist["Date"], df_test["Date"], df_future["Date"]]).drop_duplicates()
# nearest_date = all_dates.iloc[(all_dates - sel_ts).abs().argsort().iloc[0]]
# 
# if nearest_date != sel_ts:
#     st.caption(
#         f"Tanggal {selected_date.strftime('%d %b %Y')} bukan hari bursa / di luar data. "
#         f"Menampilkan tanggal terdekat: **{nearest_date.strftime('%d %b %Y')}**."
#     )
# 
# row_hist = df_hist[df_hist["Date"] == nearest_date]
# row_test = df_test[df_test["Date"] == nearest_date]
# row_future = df_future[df_future["Date"] == nearest_date]
# 
# c1, c2, c3, c4 = st.columns(4)
# c1.metric("Aktual", f"{row_hist['USD_IDR'].values[0]:,.0f}" if not row_hist.empty else "—")
# c2.metric("Prediksi ARIMA", f"{row_test['ARIMA'].values[0]:,.0f}" if not row_test.empty and not np.isnan(row_test['ARIMA'].values[0]) else "—")
# c3.metric("Prediksi LSTM", f"{row_test['LSTM'].values[0]:,.0f}" if not row_test.empty and not np.isnan(row_test['LSTM'].values[0]) else "—")
# c4.metric("Peramalan ke Depan", f"{row_future['Forecast'].values[0]:,.0f}" if not row_future.empty else "—")
# 
# 
# # --------------------------------------------------------------------------
# # TABEL PERBANDINGAN MODEL
# # --------------------------------------------------------------------------
# st.subheader("🏆 Perbandingan Performa Model (Data Uji)")
# st.dataframe(df_compare, use_container_width=True, hide_index=True)
# 
# st.caption(
#     "Pedoman interpretasi MAPE (Lewis, 1982): <10% sangat akurat · 10–20% baik · "
#     "20–50% layak/cukup · >50% tidak akurat."
# )
# 
# # --------------------------------------------------------------------------
# # DATA MENTAH (opsional, bisa dilihat & diunduh)
# # --------------------------------------------------------------------------
# with st.expander("📄 Lihat data mentah pada rentang tanggal terpilih"):
#     tab1, tab2, tab3 = st.tabs(["Aktual", "Prediksi Data Uji", "Peramalan ke Depan"])
#     with tab1:
#         st.dataframe(hist_f, use_container_width=True, hide_index=True)
#     with tab2:
#         st.dataframe(test_f, use_container_width=True, hide_index=True)
#     with tab3:
#         st.dataframe(future_f, use_container_width=True, hide_index=True)
